### PR TITLE
Fix "comparison of Array with Array failed (ArgumentError)"

### PR DESCRIPTION
**Pull request by smeyfroi**
Trying to profile something complicated threw "comparison of Array with Array failed (ArgumentError)". The fix in this PR appears to work around, though I admit to not understanding why element 0 of a row might be nil?

### CODE REVIEW

**Comment by SamSaffron** [comment]
I would really like to get to the root cause here, noticed something similar when profiling Discourse under 2.2 (which was not happening in 2.1) let me debug through it before ironing around the bug.

**Comment by smeyfroi** [comment]
NP. I can reproduce the problem and dump the array of rows if that would help. I'm using ruby2.2 with the AWS SDK v2, which is where most of my memory allocations are happening.

**Comment by SamSaffron** [comment]
ok this is fixed via:

**Comment by SamSaffron** [comment]
https://github.com/SamSaffron/memory_profiler/commit/183a3f5adcf2c8adc2ecb18fb0304a084fc18dea

**Pull request closed without merging**
