### PR TITLE
To fix a bug in top_n.rb

### PR DESCRIPTION
**Pull request by Kauperwood**
Error message:
/home/user/.rvm/gems/ruby-2.1.5@wyzyr/gems/memory_profiler-0.9.6/lib/memory_profiler/top_n.rb:12:in `sort_by': comparison of Array with Array failed (ArgumentError)

### CODE REVIEW

**Comment by dgynn** [comment]
Thanks for the report and a fix. I'd like to see if we could track down the cause. It looks like one of the metrics (gem, class, file, or location) is reporting as `nil` which would cause this problem. Could you add something like this to your rescue block and try to identify what object and metric is causing the issue?
```ruby
      puts "Checking metric #{metric}"
      puts self.values
```

**Comment by Kauperwood** [comment]
I'v did this, but my report very big and I couldn't add him to github. 
But this data: 
allocated memory by class -----------------------------------          0   
allocated objects by class -----------------------------------          0   
may be the cause of an exception. 


26 ноября 2015, 21:13:27, от "Dave Gynn" < notifications@github.com >: 

Thanks for the report and a fix. I'd like to see if we could track down the cause. It looks like one of the metrics (gem, class, file, or location) is reporting as nil which would cause this problem. Could you add something like this to your rescue block and try to identify what object and metric is causing the issue?       puts " Checking metric #{ metric } " 
      puts self .values — 
Reply to this email directly or view it on GitHub . 

-- 
With Best regards, 
Oleksii Nosach

**Comment by dgynn** [comment]
Great. That narrows it down to the class name lookup. I've just pushed a change for how we check the class name. Could you try pointing your Gemfile to the master branch and see if that resolves it?

**Comment by Kauperwood** [comment]
What does that mean " pointing a Gemfile to the master branch"? 
I'm not understand. 

27 ноября 2015, 01:05:09, от "Dave Gynn" < notifications@github.com >: 

Great. That narrows it down to the class name lookup. I've just pushed a change for how we check the class name. Could you try pointing your Gemfile to the master branch and see if that resolves it? — 
Reply to this email directly or view it on GitHub . 

-- 
With Best regards, 
Oleksii Nosach

**Comment by dgynn** [comment]
Change your Gemfile to have...
```ruby
gem 'memory_profiler', :github => 'SamSaffron/memory_profiler', :branch => 'master'
```
and run `bundle update`

**Comment by Kauperwood** [comment]
It's ok,working. You've found good decision than me. 

27 ноября 2015, 01:45:54, от "Dave Gynn" < notifications@github.com >: 

Change your Gemfile to have... gem  ' memory_profiler ' , :github  => ' SamSaffron/memory_profiler ' , :branch  => ' master ' and run bundle update — 
Reply to this email directly or view it on GitHub . 

-- 
With Best regards, 
Oleksii Nosach

**Comment by dgynn** [comment]
Great. I'm glad that worked out. This fix will be in the next release.

**Pull request closed without merging**
