### PR TITLE
Add frozen_string_literal magic comment

### PR DESCRIPTION
**Pull request by RST-J**
I added the frozen_string_literal magic comment and adjusted the tests to use non-frozen strings where needed. However, there is one test that now only allocates 45 strings instead of the 55 before.

I just adjusted the number in the test, I couldn't reasonably grasp how/whether this makes sense. This is why this is an extra commit.

P.S.: And I added .byebug_history to the .gitignore. I hope you don't mind.

### CODE REVIEW

**Comment by RST-J** [comment]
The specs for 2.1 an 2.2.10 failed (of course). One idea to fix this would be to have different versions of the respective specs/spec files that are executed depending on the ruby version. What do you think about that?

**Comment by SamSaffron** [comment]
@dgynn can you help out here? I think that was the test we added for the long string optimisation?

**Comment by RST-J** [comment]
I added a 'fix' for the broken specs due to lacking +'string' support prior to 2.3 but I'm not so confident with that. What do you think?

**Comment by SamSaffron** [comment]
Oh .. I think we can drop all official 2.2 support per: 

https://www.ruby-lang.org/en/news/2018/06/20/support-of-ruby-2-2-has-ended/

People can always install earlier versions of the gem if them must.

**Comment by SamSaffron** [comment]
Cool, Thanks heaps for the changes

**Comment by SamSaffron** [comment]
@dgynn I bumped it 👍  I hope this stabilizes the test suite too

**Pull request merged**
