### PR TITLE
Test cleanup

### PR DESCRIPTION
**Pull request by dgynn**
This PR adds Ruby 2.4.0 to the mix and simplifies the shared block creation. Making that step simpler allows Ruby 2.4 and earlier to produce the same results.

This PR also merges the TestStartStopApi methods into TestReporterStartStop class. Since both classes were extending TestReporter that meant all of the tests in the base class were being run twice and really there are just 2 additional cases related to start/stop.

### CODE REVIEW

**Comment by SamSaffron** [comment]
Awesome! thanks

**Comment by SamSaffron** [comment]
very strange, getting errors on macOS

```
sams-MBP:memory_profiler sam$ bundle exec rake
Run options: --seed 34143

# Running:

.........FF...F.......F......F...F..F........

Fabulous run in 0.712032s, 63.1994 runs/s, 137.6343 assertions/s.

  1) Failure:
TestReporter#test_ignore_file_with_regex [/Users/sam/Source/memory_profiler/test/test_reporter.rb:97]:
Expected: 3
  Actual: 1


  2) Failure:
TestReporter#test_counts [/Users/sam/Source/memory_profiler/test/test_reporter.rb:78]:
Expected: 16
  Actual: 14


  3) Failure:
TestReporter#test_ignore_file_with_string [/Users/sam/Source/memory_profiler/test/test_reporter.rb:103]:
Expected: 3
  Actual: 1


  4) Failure:
TestReporterStartStop#test_ignore_file_with_regex [/Users/sam/Source/memory_profiler/test/test_reporter.rb:97]:
Expected: 3
  Actual: 1


  5) Failure:
TestReporterStartStop#test_counts [/Users/sam/Source/memory_profiler/test/test_reporter.rb:78]:
Expected: 16
  Actual: 14


  6) Failure:
TestReporterStartStop#test_ignore_file_with_string [/Users/sam/Source/memory_profiler/test/test_reporter.rb:103]:
Expected: 3
  Actual: 1


  7) Failure:
TestReporterStartStop#test_module_double_start [/Users/sam/Source/memory_profiler/test/test_reporter_start_stop.rb:32]:
Expected: 17
  Actual: 15

45 runs, 98 assertions, 7 failures, 0 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -I"lib" -I"/Users/sam/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-10.1.0/lib" "/Users/sam/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-10.1.0/lib/rake/rake_test_loader.rb" "test/test_*.rb" ]

Tasks: TOP => default => test
(See full trace by running task with --trace)
sams-MBP:memory_profiler sam$ ruby --version
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
```

**Comment by dgynn** [comment]
That is very strange. I'm using rvm but I have the same version of ruby.

```
dgynn@grendel ~/code/dg/memory_profiler $ SEED=34143 bundle exec rake 
Run options: --seed 34143

# Running:

.............................................

Fabulous run in 0.594088s, 75.7464 runs/s, 178.4247 assertions/s.

45 runs, 106 assertions, 0 failures, 0 errors, 0 skips
dgynn@grendel ~/code/dg/memory_profiler $ ruby --version
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
```

Can you modify a test to print the results and compare where the difference is with ruby 2.3.3? With the original code, I was only getting a difference for 1 test case and it was related to the `lambda` block which is why I switched it to `profiled_block ||= -> { default_block }`.

**Comment by SamSaffron** [comment]
I will spend some time debugging tomorrow. could be something specific
about my test machine

**Comment by benoittgt** [comment]
Same here:

```sh
» SEED=34143 bundle exec rake
Run options: --seed 34143

# Running:

.............................................

Fabulous run in 0.827098s, 54.4071 runs/s, 128.1589 assertions/s.

45 runs, 106 assertions, 0 failures, 0 errors, 0 skips
```
With 2.4.0, rvm and osx.

Thanks for the PR.

**Comment by SamSaffron** [comment]
I still need to test on my macbook pro (which is not with me atm) but for
the time being it passed on my Linux box just fine so I pushed a new
version out there

**Pull request merged**
