### PR TITLE
Allow hacky String-based classes instantiations

### PR DESCRIPTION
**Pull request by inossidabile**

### CODE REVIEW

**Comment by dgynn** [comment]
Can you give an example of what this fixes?

**Comment by inossidabile** [comment]
Similarly to #27 where in a special case `klass` was evaluated to nil, I get it evaluated to `String`. String, obviously, doesn't have `.name`.

**Comment by dgynn** [comment]
Yeah. I'd love to know how that object or class was created so we're handling any other special cases we hadn't considered. Could you see if you can track down what the object was or if it came from some other gem so we can add a test case for it?

**Comment by inossidabile** [comment]
I believe it's instantiated by Mechanize. I can do some tracking later, yes. Just needed something working right now and decided it was the best way to notify about the issue.

**Comment by dgynn** [comment]
Great. I've added a test case and tweaked the implementation in case other non-Class objects respond to `:name`. 

Thanks for the fix!

**Pull request merged**
